# Generated by Django 2.2 on 2020-05-09 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('RS', 'Roadster'), ('PM', 'Puma'), ('WR', 'WROGN'), ('FC', 'Fort Collins'), ('HR', 'HRX'), ('HN', 'HERE & NOW'), ('MH', 'Mast & Harbour'), ('CS', 'Campus Sutra'), ('MR', 'Moda Rapido'), ('AD', 'Adidas'), ('KK', 'Kook & Keech'), ('LO', 'Locomotive'), ('HL', 'HIGH LANDER')], max_length=2)),
                ('title', models.CharField(max_length=30)),
                ('sex_type', models.CharField(choices=[('M', 'MEN'), ('W', 'WOMEN')], max_length=2)),
                ('cloth_type', models.CharField(choices=[('TS', 'T-Shirts'), ('FS', 'Formal Shirts'), ('CS', 'Casual Shirts'), ('JS', 'Jackets')], max_length=2)),
                ('wear_type', models.CharField(choices=[('TP', 'Top Wear'), ('BW', 'Botom Wear'), ('IW', 'Inner Wear'), ('FW', 'Festive Wear'), ('IW', 'Indian Wear'), ('WW', 'Western Wear')], max_length=2)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra Large'), ('XXL', 'Xtra Xtra Large')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='estore.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
